### ISSUE TITLE
Can We Talk About This?

### ISSUE THREAD

**Issue by ac360** [marklawlor/serverless-swagger#13]
Hi @marklawlor,

Great work here.  I'm wondering if we could chat about this and what we can do on our end to help you.  Please email me at austen@jawsframework.com

**Comment by JamieCressey** [comment]
+1 was there any update to this?

**Comment by marklawlor** [comment]
Hey @JamieCressey, I spoke with the Serverless guys shortly before the Christmas break. I've just returned from holidays and hope to get this back into development.
