### ISSUE TITLE
Serverless Classes

### ISSUE THREAD

**Issue by ac360** [marklawlor/serverless-swagger#15]
Mark, 

You were right.  We've put classes that Plugin Authors can use in the main Serverless Class.  Please take a look at these and let me know what you think:

https://github.com/serverless/serverless/blob/v0.1.0/lib/Serverless.js#L46

Hope you are well :)

Kind regards,
Austen

**Comment by marklawlor** [comment]
Looks good! :+1: This will make things much easier for other developers.
